name: ci.uffs.cc
on: push
env:
  BUILD_HOST: ci.uffs.cc
  BUILD_WEB_DIRECTORY: /home/ccuffsci/ci.uffs.cc/practice-api
  BUILD_WEB_URL: https://ci.uffs.cc/practice-api
jobs:
  build-deploy-audit:
    name: Build, deploy and audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Prepare deploy server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.BUILD_HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          mkdir -p ${{ env.BUILD_WEB_DIRECTORY }}/${{ steps.extract_branch.outputs.branch }}/${{ github.sha }}
          mkdir -p ${{ env.BUILD_WEB_DIRECTORY }}/${{ steps.extract_branch.outputs.branch }}/${{ github.sha }}/_report
    - name: Deploy site via SSH
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ${{ github.workspace }}/
        remote: ${{ env.BUILD_WEB_DIRECTORY }}/${{ steps.extract_branch.outputs.branch }}/${{ github.sha }}/
        host: ${{ env.BUILD_HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
    - name: Summary
      run: |
        echo "Summary:"
        echo " Live URL: ${{ env.BUILD_WEB_URL }}/${{ steps.extract_branch.outputs.branch }}/${{ github.sha }}"
